# PostgreSQL. Versions 9.3 and up are supported.

default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: postgres
  password: postgres
  port: 5432
  host: localhost

development:
  <<: *default
  database: ror_coding_assignment_development

test:
  <<: *default
  database: ror_coding_assignment_test

production:
  <<: *default
  database: ror_coding_assignment_production
  username: ror_coding_assignment
  password: <%= ENV["ROR_CODING_ASSIGNMENT_DATABASE_PASSWORD"] %>
